
###
GET http://localhost:3001/account

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "email":"tahsinr98@gmail.com",
    "password":"Tomti1998"
}

###
GET http://localhost:3001/user/6364580ed22165fde299fa8e
###
GET http://localhost:3001/profile/6364580ed22165fde299fa8e

###
POST http://localhost:3001/createrecipe/6364580ed22165fde299fa8e
Content-Type: application/json

{
    "AuthorName": "Tahsin ",
    "RecipeName": "Toast",
    "category": "breakfast",
    "instruction": "spread eggs on bread and fry",
    "ingredientList": "eggs, bread, salt",
    "Rating": "4",
    "UserID": "6364580ed22165fde299fa8e"
}

###
GET http://localhost:3001/userrecipes/6364580ed22165fde299fa8e